'use strict';

// Keeper-only barrel. The owner-kernel trust machinery (kernel, event ledger,
// witness chain, acceptance predicate, shadow translation) was retired on
// 2026-08-16 — rationale, review chain, and quarry anchors in
// docs/plans/2026-08-16-owner-kernel-retirement.md. These five primitives and
// the mission re-exports remain because live engine/mission/profile code and
// their tests resolve them through this barrel.

const { canonicalJson, cloneCanonical, isSha256, sha256 } = require('./canonical');
const {
  ACTION_CLASS_RANK,
  assertIndependentAuthorityBindings,
  actionDescriptorHash,
  actionMatchesDescriptor,
  normalizeActionAuthority,
  normalizeActionCancellationResult,
  normalizeActionCatalog,
  normalizeActionDescriptor,
  normalizeActionExecutionResult,
  normalizeExecutionAuthorization,
  normalizeExecutionPermit,
  normalizeFrozenActionDescriptor,
  normalizeFrozenHostCapabilityVerifierBinding,
  normalizeHostCapability,
  normalizeVerifiedActionOutcome,
  receiptIsWithinBrokerRoot,
  validateHostCapabilityCoverage,
} = require('./actions');
const { OwnerKernelBlockedError, OwnerKernelError } = require('./errors');
const {
  ACTION_CLASSES,
  ASSURANCE_PROFILES,
  DATA_EGRESS_MODES,
  GOVERNANCE_SCHEMA_VERSION,
  GUIDANCE_PROFILES,
  SUPPORTED_MODES,
  TOPOLOGY_PREFERENCES,
  freezeAcceptanceContract,
  resolveGovernancePolicy,
} = require('./policy');
const {
  ACTION_CLASS_ORDER,
  AUTHORITY_STATUS,
  DATA_CLASSES,
  EGRESS_MODE_RANK,
  PAYLOAD_CLASSIFICATIONS,
  PAYLOAD_CLASSIFICATION_RANK,
  REQUIRED_RECEIPT_FIELDS,
  ROLES,
  ROUTE_CLASSES,
  TASK_AUTHORITY_SCHEMA_VERSION,
  actionClassRank,
  egressDecision,
  freezeTaskAuthorityEnvelope,
  normalizeTaskAuthorityEnvelope,
  verifyTaskAuthorityEnvelope,
} = require('./task-authority');
const {
  MISSION_POLICY_FIELDS,
  MISSION_POLICY_SCHEMA_VERSION,
  deriveMissionAdoptionKey,
  deriveMissionLineageId,
  resolveMissionLineageAdoption,
  resolveMissionPolicy,
  validateEffectiveMissionPolicy,
} = require('../mission-policy');
const {
  MISSION_GRAPH_SCHEMA_VERSION,
  admitMissionExecutionGraph,
  checkMissionGraphCoverage,
  deriveMissionGraphNodeDigest,
  freezeMissionExecutionGraph,
  validateMissionExecutionGraph,
} = require('../mission-execution-graph');

module.exports = {
  ACTION_CLASSES,
  ACTION_CLASS_ORDER,
  ACTION_CLASS_RANK,
  ASSURANCE_PROFILES,
  AUTHORITY_STATUS,
  DATA_CLASSES,
  DATA_EGRESS_MODES,
  EGRESS_MODE_RANK,
  GOVERNANCE_SCHEMA_VERSION,
  GUIDANCE_PROFILES,
  MISSION_GRAPH_SCHEMA_VERSION,
  MISSION_POLICY_FIELDS,
  MISSION_POLICY_SCHEMA_VERSION,
  OwnerKernelBlockedError,
  OwnerKernelError,
  PAYLOAD_CLASSIFICATIONS,
  PAYLOAD_CLASSIFICATION_RANK,
  REQUIRED_RECEIPT_FIELDS,
  ROLES,
  ROUTE_CLASSES,
  SUPPORTED_MODES,
  TASK_AUTHORITY_SCHEMA_VERSION,
  TOPOLOGY_PREFERENCES,
  actionClassRank,
  actionDescriptorHash,
  actionMatchesDescriptor,
  admitMissionExecutionGraph,
  assertIndependentAuthorityBindings,
  canonicalJson,
  checkMissionGraphCoverage,
  cloneCanonical,
  deriveMissionAdoptionKey,
  deriveMissionGraphNodeDigest,
  deriveMissionLineageId,
  egressDecision,
  freezeAcceptanceContract,
  freezeMissionExecutionGraph,
  freezeTaskAuthorityEnvelope,
  isSha256,
  normalizeActionAuthority,
  normalizeActionCancellationResult,
  normalizeActionCatalog,
  normalizeActionDescriptor,
  normalizeActionExecutionResult,
  normalizeExecutionAuthorization,
  normalizeExecutionPermit,
  normalizeFrozenActionDescriptor,
  normalizeFrozenHostCapabilityVerifierBinding,
  normalizeHostCapability,
  normalizeTaskAuthorityEnvelope,
  normalizeVerifiedActionOutcome,
  receiptIsWithinBrokerRoot,
  resolveGovernancePolicy,
  resolveMissionLineageAdoption,
  resolveMissionPolicy,
  sha256,
  validateEffectiveMissionPolicy,
  validateHostCapabilityCoverage,
  validateMissionExecutionGraph,
  verifyTaskAuthorityEnvelope,
};
