'use strict';

const { canonicalJson, cloneCanonical, isSha256, sha256 } = require('./canonical');
const {
  classifyContractLeg,
  contractArtifactIds,
  evaluateAcceptancePredicate,
  manifestHash,
  normalizeAcceptanceAuthority,
  normalizeAcceptanceAuthorityHeader,
  normalizeAcceptanceSnapshot,
} = require('./acceptance');
const {
  ACTION_CLASS_RANK,
  assertIndependentAuthorityBindings,
  actionDescriptorHash,
  actionMatchesDescriptor,
  normalizeActionAuthority,
  normalizeActionCancellationResult,
  normalizeActionCatalog,
  normalizeActionDescriptor,
  normalizeActionExecutionResult,
  normalizeExecutionAuthorization,
  normalizeExecutionPermit,
  normalizeFrozenActionDescriptor,
  normalizeFrozenHostCapabilityVerifierBinding,
  normalizeHostCapability,
  normalizeVerifiedActionOutcome,
  receiptIsWithinBrokerRoot,
  validateHostCapabilityCoverage,
} = require('./actions');
const { OwnerKernelBlockedError, OwnerKernelError } = require('./errors');
const { EVENT_TYPES, OWNER_EVENT_SCHEMA_VERSION, validateEventShape, verifyEvent } = require('./events');
const { OwnerKernel } = require('./kernel');
const {
  HEADER_RECORD_TYPE,
  LEDGER_SCHEMA_VERSION,
  createLedgerHeader,
  parseLedgerJsonl,
  replayFromLatestCheckpoint,
  serializeLedger,
  validateLedgerHeader,
  verifyLedger,
} = require('./ledger');
const {
  ACTION_CLASSES,
  DATA_EGRESS_MODES,
  GOVERNANCE_SCHEMA_VERSION,
  GUIDANCE_PROFILES,
  SUPPORTED_MODES,
  TOPOLOGY_PREFERENCES,
  freezeAcceptanceContract,
  resolveGovernancePolicy,
} = require('./policy');
const {
  ACTION_CLASS_ORDER,
  AUTHORITY_STATUS,
  DATA_CLASSES,
  EGRESS_MODE_RANK,
  PAYLOAD_CLASSIFICATIONS,
  PAYLOAD_CLASSIFICATION_RANK,
  REQUIRED_RECEIPT_FIELDS,
  ROLES,
  ROUTE_CLASSES,
  TASK_AUTHORITY_SCHEMA_VERSION,
  actionClassRank,
  egressDecision,
  freezeTaskAuthorityEnvelope,
  normalizeTaskAuthorityEnvelope,
  verifyTaskAuthorityEnvelope,
} = require('./task-authority');
const { deriveDisclosure, stateProjection } = require('./state');
const { MemoryWitness, normalizeWitnessBinding } = require('./witness');
const {
  SEMANTIC_AUTHORITY_SCHEMA_VERSION,
  SEMANTIC_WITNESS_ROUTE_VERSION,
  createSemanticAuthorityHeader,
  normalizeSemanticAuthorityHeader,
  normalizeSemanticRoute,
  semanticRouteHash,
} = require('./semantic-authority');
const {
  ASSURANCE_PROFILES,
  LEGACY_LEVELS,
  LEVEL_TOPOLOGIES,
  LEVEL_TRANSLATION_SCHEMA_VERSION,
  createShadowTranslationEnvelope,
  deriveTranslationStatus,
  normalizeRedLines,
  translateLegacyLevel,
  verifyShadowTranslationEnvelope,
} = require('./compatibility');
const {
  SHADOW_TRANSLATION_CONTRACT_ID,
  SHADOW_TRANSLATION_LEVEL,
  ShadowTranslationRuntime,
} = require('./shadow-translation');
const {
  MISSION_POLICY_FIELDS,
  MISSION_POLICY_SCHEMA_VERSION,
  deriveMissionAdoptionKey,
  deriveMissionLineageId,
  resolveMissionLineageAdoption,
  resolveMissionPolicy,
  validateEffectiveMissionPolicy,
} = require('../mission-policy');
const {
  MISSION_GRAPH_SCHEMA_VERSION,
  admitMissionExecutionGraph,
  checkMissionGraphCoverage,
  deriveMissionGraphNodeDigest,
  freezeMissionExecutionGraph,
  validateMissionExecutionGraph,
} = require('../mission-execution-graph');

module.exports = {
  ACTION_CLASSES,
  ACTION_CLASS_ORDER,
  ACTION_CLASS_RANK,
  ASSURANCE_PROFILES,
  AUTHORITY_STATUS,
  DATA_CLASSES,
  DATA_EGRESS_MODES,
  EGRESS_MODE_RANK,
  PAYLOAD_CLASSIFICATIONS,
  PAYLOAD_CLASSIFICATION_RANK,
  assertIndependentAuthorityBindings,
  EVENT_TYPES,
  GOVERNANCE_SCHEMA_VERSION,
  GUIDANCE_PROFILES,
  HEADER_RECORD_TYPE,
  LEDGER_SCHEMA_VERSION,
  LEGACY_LEVELS,
  LEVEL_TOPOLOGIES,
  LEVEL_TRANSLATION_SCHEMA_VERSION,
  MemoryWitness,
  MISSION_GRAPH_SCHEMA_VERSION,
  MISSION_POLICY_FIELDS,
  MISSION_POLICY_SCHEMA_VERSION,
  OWNER_EVENT_SCHEMA_VERSION,
  OwnerKernel,
  OwnerKernelBlockedError,
  OwnerKernelError,
  REQUIRED_RECEIPT_FIELDS,
  ROLES,
  ROUTE_CLASSES,
  SHADOW_TRANSLATION_CONTRACT_ID,
  SHADOW_TRANSLATION_LEVEL,
  SEMANTIC_AUTHORITY_SCHEMA_VERSION,
  SEMANTIC_WITNESS_ROUTE_VERSION,
  ShadowTranslationRuntime,
  SUPPORTED_MODES,
  TASK_AUTHORITY_SCHEMA_VERSION,
  TOPOLOGY_PREFERENCES,
  actionClassRank,
  canonicalJson,
  classifyContractLeg,
  cloneCanonical,
  contractArtifactIds,
  createLedgerHeader,
  createSemanticAuthorityHeader,
  createShadowTranslationEnvelope,
  deriveTranslationStatus,
  deriveDisclosure,
  deriveMissionAdoptionKey,
  deriveMissionLineageId,
  deriveMissionGraphNodeDigest,
  egressDecision,
  evaluateAcceptancePredicate,
  freezeAcceptanceContract,
  freezeTaskAuthorityEnvelope,
  freezeMissionExecutionGraph,
  isSha256,
  actionDescriptorHash,
  actionMatchesDescriptor,
  normalizeActionAuthority,
  normalizeAcceptanceAuthority,
  normalizeAcceptanceAuthorityHeader,
  normalizeAcceptanceSnapshot,
  normalizeActionCancellationResult,
  normalizeActionCatalog,
  normalizeActionDescriptor,
  normalizeActionExecutionResult,
  normalizeExecutionAuthorization,
  normalizeExecutionPermit,
  normalizeFrozenActionDescriptor,
  normalizeFrozenHostCapabilityVerifierBinding,
  normalizeHostCapability,
  normalizeRedLines,
  normalizeSemanticAuthorityHeader,
  normalizeSemanticRoute,
  normalizeTaskAuthorityEnvelope,
  normalizeWitnessBinding,
  normalizeVerifiedActionOutcome,
  manifestHash,
  parseLedgerJsonl,
  replayFromLatestCheckpoint,
  resolveGovernancePolicy,
  resolveMissionPolicy,
  resolveMissionLineageAdoption,
  validateEffectiveMissionPolicy,
  receiptIsWithinBrokerRoot,
  serializeLedger,
  semanticRouteHash,
  sha256,
  stateProjection,
  translateLegacyLevel,
  validateEventShape,
  validateHostCapabilityCoverage,
  validateLedgerHeader,
  verifyEvent,
  verifyLedger,
  verifyShadowTranslationEnvelope,
  verifyTaskAuthorityEnvelope,
  admitMissionExecutionGraph,
  checkMissionGraphCoverage,
  validateMissionExecutionGraph,
};
