'use strict';

const {
  AutopilotEngine,
  buildImplementationArgs,
  buildReviewArgs,
  reviewLoopResultBlocked,
  reviewResultBlocked,
  validateImplementerRoster,
  validateExtraReviewArgs,
  validateExtraArgs,
  validateReviewRoster,
} = require('./autopilot-engine');

const {
  ENGINE_LIFECYCLE_OBSERVATION_SCHEMA_VERSION,
  OBSERVATION_DISCLOSURE,
  EngineLifecycleObservationSession,
  createEngineLifecycleObservationSession,
  normalizeEngineLifecycleObservationConfig,
} = require('./engine-lifecycle-observation');

const {
  BoundedUnixLifecycleObserver,
  EXTERNAL_LIFECYCLE_WITNESS_PROTOCOL_VERSION,
  ExternalLifecycleWitnessDaemon,
  createBoundedUnixLifecycleObserver,
  invokeSocketRequest,
  normalizeClientConfig: normalizeExternalLifecycleWitnessClientConfig,
  normalizeDaemonConfig: normalizeExternalLifecycleWitnessDaemonConfig,
} = require('./external-lifecycle-witness');

const {
  AUTOPILOT_ENGINE_CONTROL_SINKS,
  AUTOPILOT_ENGINE_RUNTIME_CONTEXT_OPTION_KEYS,
  ENGINE_BRIDGE_CONTRACT_SCHEMA_VERSION,
  TRUSTED_INTAKE_VERIFICATION_PATH,
  compileSupervisedEngineBridgeContract,
  getAutopilotEngineControlSinkInventory,
  getRequiredActionCatalogBindingIds,
  getSupervisedEngineBridgeAbi,
  getSupervisedEngineBridgeAbiHash,
  validateAutopilotEngineControlSinkInventory,
  verifySupervisedEngineBridgeContract,
} = require('./supervised-engine-bridge-contract');

const {
  MAX_FRAME_BYTES: SUPERVISED_HOST_MAX_FRAME_BYTES,
  REQUEST_TIMEOUT_MILLISECONDS: SUPERVISED_HOST_REQUEST_TIMEOUT_MILLISECONDS,
  RUNTIME_PARENT: SUPERVISED_HOST_RUNTIME_PARENT,
  SOCKET_DIRECTORY: SUPERVISED_HOST_SOCKET_DIRECTORY,
  SOCKET_FILENAME: SUPERVISED_HOST_SOCKET_FILENAME,
  STATE_DIRECTORY: SUPERVISED_HOST_STATE_DIRECTORY,
  SUPERVISED_HOST_PREFLIGHT_SCHEMA_VERSION,
  SUPERVISED_HOST_PROTOCOL_VERSION,
  SUPERVISED_HOST_SYSTEMD_PROPERTIES,
  SYSTEMD_WORKER_GID,
  SYSTEMD_WORKER_IDENTITY,
  SYSTEMD_WORKER_UID,
  SYSTEMD_SLICE: SUPERVISED_HOST_SYSTEMD_SLICE,
  buildSupervisedHostGatewayArgs,
  buildSupervisedHostSystemdArgs,
  buildSupervisedHostWorkerArgs,
  compileSupervisedHostPreflight,
  preflightSupervisedHostRuntime,
  verifySupervisedHostPreflight,
} = require('./supervised-host-preflight');

const {
  resolveReviewLoop,
  resolveReviewLoopJson,
  parseReviewLoopOutput,
  validateReviewLoopConfig,
  findJsonObjectCandidates,
  looksLikeReviewLoopConfig,
  RESOLVE_REVIEW_LOOP,
} = require('./resolve-review-loop');

const ownerKernel = require('./owner-kernel');

module.exports = {
  AutopilotEngine,
  AUTOPILOT_ENGINE_CONTROL_SINKS,
  AUTOPILOT_ENGINE_RUNTIME_CONTEXT_OPTION_KEYS,
  BoundedUnixLifecycleObserver,
  ENGINE_BRIDGE_CONTRACT_SCHEMA_VERSION,
  SUPERVISED_HOST_MAX_FRAME_BYTES,
  SUPERVISED_HOST_PREFLIGHT_SCHEMA_VERSION,
  SUPERVISED_HOST_PROTOCOL_VERSION,
  SUPERVISED_HOST_REQUEST_TIMEOUT_MILLISECONDS,
  SUPERVISED_HOST_RUNTIME_PARENT,
  SUPERVISED_HOST_SOCKET_DIRECTORY,
  SUPERVISED_HOST_SOCKET_FILENAME,
  SUPERVISED_HOST_STATE_DIRECTORY,
  SUPERVISED_HOST_SYSTEMD_PROPERTIES,
  SYSTEMD_WORKER_GID,
  SYSTEMD_WORKER_IDENTITY,
  SYSTEMD_WORKER_UID,
  SUPERVISED_HOST_SYSTEMD_SLICE,
  TRUSTED_INTAKE_VERIFICATION_PATH,
  ENGINE_LIFECYCLE_OBSERVATION_SCHEMA_VERSION,
  EXTERNAL_LIFECYCLE_WITNESS_PROTOCOL_VERSION,
  OBSERVATION_DISCLOSURE,
  EngineLifecycleObservationSession,
  ExternalLifecycleWitnessDaemon,
  buildImplementationArgs,
  buildReviewArgs,
  buildSupervisedHostGatewayArgs,
  buildSupervisedHostSystemdArgs,
  buildSupervisedHostWorkerArgs,
  createBoundedUnixLifecycleObserver,
  createEngineLifecycleObservationSession,
  compileSupervisedEngineBridgeContract,
  compileSupervisedHostPreflight,
  getAutopilotEngineControlSinkInventory,
  getRequiredActionCatalogBindingIds,
  getSupervisedEngineBridgeAbi,
  getSupervisedEngineBridgeAbiHash,
  reviewLoopResultBlocked,
  reviewResultBlocked,
  validateExtraArgs,
  validateImplementerRoster,
  validateExtraReviewArgs,
  validateReviewRoster,
  normalizeEngineLifecycleObservationConfig,
  normalizeExternalLifecycleWitnessClientConfig,
  normalizeExternalLifecycleWitnessDaemonConfig,
  resolveReviewLoop,
  resolveReviewLoopJson,
  parseReviewLoopOutput,
  preflightSupervisedHostRuntime,
  validateAutopilotEngineControlSinkInventory,
  validateReviewLoopConfig,
  verifySupervisedEngineBridgeContract,
  verifySupervisedHostPreflight,
  findJsonObjectCandidates,
  looksLikeReviewLoopConfig,
  RESOLVE_REVIEW_LOOP,
  invokeSocketRequest,
  ...ownerKernel,
};
