'use strict';

const {
  AutopilotEngine,
  buildImplementationArgs,
  buildReviewArgs,
  reviewLoopResultBlocked,
  reviewResultBlocked,
  validateImplementerRoster,
  validateExtraReviewArgs,
  validateExtraArgs,
  validateReviewRoster,
} = require('./autopilot-engine');

const {
  ENGINE_LIFECYCLE_OBSERVATION_SCHEMA_VERSION,
  OBSERVATION_DISCLOSURE,
  EngineLifecycleObservationSession,
  createEngineLifecycleObservationSession,
  normalizeEngineLifecycleObservationConfig,
} = require('./engine-lifecycle-observation');

const {
  BoundedUnixLifecycleObserver,
  EXTERNAL_LIFECYCLE_WITNESS_PROTOCOL_VERSION,
  ExternalLifecycleWitnessDaemon,
  createBoundedUnixLifecycleObserver,
  invokeSocketRequest,
  normalizeClientConfig: normalizeExternalLifecycleWitnessClientConfig,
  normalizeDaemonConfig: normalizeExternalLifecycleWitnessDaemonConfig,
} = require('./external-lifecycle-witness');

const {
  AUTOPILOT_ENGINE_CONTROL_SINKS,
  AUTOPILOT_ENGINE_RUNTIME_CONTEXT_OPTION_KEYS,
  ENGINE_BRIDGE_CONTRACT_SCHEMA_VERSION,
  TRUSTED_INTAKE_VERIFICATION_PATH,
  compileSupervisedEngineBridgeContract,
  getAutopilotEngineControlSinkInventory,
  getRequiredActionCatalogBindingIds,
  getSupervisedEngineBridgeAbi,
  getSupervisedEngineBridgeAbiHash,
  normalizeSupervisedEngineTrustedIntakeBinding,
  validateAutopilotEngineControlSinkInventory,
  verifySupervisedEngineBridgeContract,
} = require('./supervised-engine-bridge-contract');

const {
  AUTHENTICATED_INTAKE_ALGORITHM,
  AUTHENTICATED_INTAKE_AUDIENCE,
  AUTHENTICATED_INTAKE_PURPOSE,
  AUTHENTICATED_INTAKE_SCHEMA_VERSION,
  AuthenticatedIntakeError,
  createFileReplayStore,
  createHostPinnedTrustedIntakeVerifier,
  createInMemoryReplayStore,
  normalizeAuthenticatedIntakeKeyring,
  parseCanonicalJsonBytes,
  verifyHostPinnedAuthenticatedIntake,
} = require('./supervised-authenticated-intake');

const {
  MAX_FRAME_BYTES: SUPERVISED_HOST_MAX_FRAME_BYTES,
  REQUEST_TIMEOUT_MILLISECONDS: SUPERVISED_HOST_REQUEST_TIMEOUT_MILLISECONDS,
  RUNTIME_PARENT: SUPERVISED_HOST_RUNTIME_PARENT,
  SOCKET_DIRECTORY: SUPERVISED_HOST_SOCKET_DIRECTORY,
  SOCKET_FILENAME: SUPERVISED_HOST_SOCKET_FILENAME,
  STATE_DIRECTORY: SUPERVISED_HOST_STATE_DIRECTORY,
  SUPERVISED_HOST_PREFLIGHT_SCHEMA_VERSION,
  SUPERVISED_HOST_PROTOCOL_VERSION,
  SUPERVISED_HOST_SYSTEMD_PROPERTIES,
  SYSTEMD_WORKER_GID,
  SYSTEMD_WORKER_IDENTITY,
  SYSTEMD_WORKER_UID,
  SYSTEMD_SLICE: SUPERVISED_HOST_SYSTEMD_SLICE,
  buildSupervisedHostGatewayArgs,
  buildSupervisedHostSystemdArgs,
  buildSupervisedHostWorkerArgs,
  compileSupervisedHostPreflight,
  preflightSupervisedHostRuntime,
  verifySupervisedHostPreflight,
} = require('./supervised-host-preflight');

const {
  BROKER_OPERATIONS: SUPERVISED_PRODUCTION_BROKER_OPERATIONS,
  COORDINATOR_OPERATIONS: SUPERVISED_PRODUCTION_COORDINATOR_OPERATIONS,
  INTAKE_PROTOCOL_VERSION: SUPERVISED_PRODUCTION_INTAKE_PROTOCOL_VERSION,
  SERVICE_ROLES: SUPERVISED_PRODUCTION_SERVICE_ROLES,
  SUPERVISED_PRODUCTION_SUBSTRATE_KIND,
  SUPERVISED_PRODUCTION_SUBSTRATE_SCHEMA_VERSION,
  SUPERVISED_PRODUCTION_SUBSTRATE_STATUS,
  SUPERVISED_SERVICE_IPC_PROTOCOL_VERSION,
  WITNESS_OPERATIONS: SUPERVISED_PRODUCTION_WITNESS_OPERATIONS,
  compileSupervisedProductionSubstrateContract,
  createAcceptanceDisabledCoordinatorResult,
  createEffectsDisabledBrokerResult,
  getSupervisedProductionSubstrateAbi,
  getSupervisedProductionSubstrateAbiHash,
  normalizeAcceptanceDisabledCoordinatorResult,
  normalizeCoordinatorRequest,
  normalizeEffectsDisabledBrokerResult,
  normalizeServiceEnvelope,
  normalizeWitnessRequest,
  verifySupervisedProductionSubstrateContract,
} = require('./supervised-production-substrate-contract');

const {
  DURABLE_ENDPOINTS: SUPERVISED_PRODUCTION_DURABLE_ENDPOINTS,
  DURABLE_STATE_PROTOCOL_VERSION: SUPERVISED_PRODUCTION_DURABLE_PROTOCOL_VERSION,
  DURABLE_STATE_SCHEMA_VERSION: SUPERVISED_PRODUCTION_DURABLE_SCHEMA_VERSION,
  MAX_DURABLE_FRAME_BYTES: SUPERVISED_PRODUCTION_DURABLE_MAX_FRAME_BYTES,
  getSupervisedProductionDurableAbi,
  getSupervisedProductionDurableAbiHash,
  normalizeDurableAvailabilityDisclosure: normalizeSupervisedProductionDurableAvailabilityDisclosure,
  normalizeCoordinatorRequest: normalizeSupervisedProductionDurableCoordinatorRequest,
  normalizeDurableBinding: normalizeSupervisedProductionDurableBinding,
  normalizeDurableBrokerResult: normalizeSupervisedProductionDurableBrokerResult,
  normalizeDurableCoordinatorResult: normalizeSupervisedProductionDurableCoordinatorResult,
  normalizeDurableEnvelope: normalizeSupervisedProductionDurableEnvelope,
  normalizeDurableRevocationResult: normalizeSupervisedProductionDurableRevocationResult,
  normalizeDurableServiceAvailabilitySnapshot: normalizeSupervisedProductionDurableServiceAvailabilitySnapshot,
  normalizeDurableWitnessResult: normalizeSupervisedProductionDurableWitnessResult,
  normalizeWitnessRequest: normalizeSupervisedProductionDurableWitnessRequest,
} = require('./supervised-production-substrate-durable-contract');

const {
  SEMANTIC_WITNESS_TRANSPORT_SCHEMA_VERSION,
  assertSemanticRouteFresh,
  compileSemanticWitnessRoute,
  createSemanticWitnessAdapter,
  createSemanticWitnessSession,
  resumeSemanticWitnessSession,
} = require('./supervised-owner-kernel-semantic-witness');

const {
  PROBE_EFFECT_CATALOG_ENTRY,
  PROBE_EFFECT_CATALOG_ID,
  PROBE_EFFECT_OPERATION,
  PROBE_EFFECT_PROFILE_VERSION,
  PROBE_EFFECT_RECEIPT_ROOT,
  PROBE_EFFECT_TARGET,
  PROBE_EFFECT_TOOL_CLASS,
  compileProbeEffectProfile,
  createProbeEffectActionAuthority,
  createProbeEffectSession,
  normalizeProbeEffectProfile,
  resumeProbeEffectSession,
} = require('./supervised-owner-kernel-probe-effect');

const {
  ENGINE_ACCEPTANCE_PROFILE_VERSION,
  ENGINE_IMPLEMENTATION_CATALOG_ENTRY,
  ENGINE_IMPLEMENTATION_CATALOG_ID,
  ENGINE_IMPLEMENTATION_OPERATION,
  ENGINE_IMPLEMENTATION_RECEIPT_ROOT,
  ENGINE_IMPLEMENTATION_TARGET,
  ENGINE_IMPLEMENTATION_TOOL_CLASS,
  compileEngineAcceptanceProfile,
  createEngineAcceptanceCoordinator,
  createEngineAcceptanceSession,
  createEngineActionAuthority,
  normalizeEngineAcceptanceProfile,
} = require('./supervised-owner-kernel-engine-acceptance');

const {
  resolveReviewLoop,
  resolveReviewLoopJson,
  parseReviewLoopOutput,
  validateReviewLoopConfig,
  findJsonObjectCandidates,
  looksLikeReviewLoopConfig,
  RESOLVE_REVIEW_LOOP,
} = require('./resolve-review-loop');

const ownerKernel = require('./owner-kernel');
const executionProfile = require('./execution-profile');

module.exports = {
  AutopilotEngine,
  AUTHENTICATED_INTAKE_ALGORITHM,
  AUTHENTICATED_INTAKE_AUDIENCE,
  AUTHENTICATED_INTAKE_PURPOSE,
  AUTHENTICATED_INTAKE_SCHEMA_VERSION,
  AUTOPILOT_ENGINE_CONTROL_SINKS,
  AUTOPILOT_ENGINE_RUNTIME_CONTEXT_OPTION_KEYS,
  BoundedUnixLifecycleObserver,
  AuthenticatedIntakeError,
  ENGINE_BRIDGE_CONTRACT_SCHEMA_VERSION,
  ENGINE_ACCEPTANCE_PROFILE_VERSION,
  ENGINE_IMPLEMENTATION_CATALOG_ENTRY,
  ENGINE_IMPLEMENTATION_CATALOG_ID,
  ENGINE_IMPLEMENTATION_OPERATION,
  ENGINE_IMPLEMENTATION_RECEIPT_ROOT,
  ENGINE_IMPLEMENTATION_TARGET,
  ENGINE_IMPLEMENTATION_TOOL_CLASS,
  SUPERVISED_HOST_MAX_FRAME_BYTES,
  SUPERVISED_HOST_PREFLIGHT_SCHEMA_VERSION,
  SUPERVISED_HOST_PROTOCOL_VERSION,
  SUPERVISED_HOST_REQUEST_TIMEOUT_MILLISECONDS,
  SUPERVISED_HOST_RUNTIME_PARENT,
  SUPERVISED_HOST_SOCKET_DIRECTORY,
  SUPERVISED_HOST_SOCKET_FILENAME,
  SUPERVISED_HOST_STATE_DIRECTORY,
  SUPERVISED_HOST_SYSTEMD_PROPERTIES,
  SUPERVISED_PRODUCTION_BROKER_OPERATIONS,
  SUPERVISED_PRODUCTION_DURABLE_ENDPOINTS,
  SUPERVISED_PRODUCTION_DURABLE_MAX_FRAME_BYTES,
  SUPERVISED_PRODUCTION_DURABLE_PROTOCOL_VERSION,
  SUPERVISED_PRODUCTION_DURABLE_SCHEMA_VERSION,
  SUPERVISED_PRODUCTION_COORDINATOR_OPERATIONS,
  SUPERVISED_PRODUCTION_INTAKE_PROTOCOL_VERSION,
  SUPERVISED_PRODUCTION_SERVICE_ROLES,
  SUPERVISED_PRODUCTION_SUBSTRATE_KIND,
  SUPERVISED_PRODUCTION_SUBSTRATE_SCHEMA_VERSION,
  SUPERVISED_PRODUCTION_SUBSTRATE_STATUS,
  SUPERVISED_PRODUCTION_WITNESS_OPERATIONS,
  SUPERVISED_SERVICE_IPC_PROTOCOL_VERSION,
  SEMANTIC_WITNESS_TRANSPORT_SCHEMA_VERSION,
  SYSTEMD_WORKER_GID,
  SYSTEMD_WORKER_IDENTITY,
  SYSTEMD_WORKER_UID,
  SUPERVISED_HOST_SYSTEMD_SLICE,
  TRUSTED_INTAKE_VERIFICATION_PATH,
  ENGINE_LIFECYCLE_OBSERVATION_SCHEMA_VERSION,
  EXTERNAL_LIFECYCLE_WITNESS_PROTOCOL_VERSION,
  OBSERVATION_DISCLOSURE,
  PROBE_EFFECT_CATALOG_ENTRY,
  PROBE_EFFECT_CATALOG_ID,
  PROBE_EFFECT_OPERATION,
  PROBE_EFFECT_PROFILE_VERSION,
  PROBE_EFFECT_RECEIPT_ROOT,
  PROBE_EFFECT_TARGET,
  PROBE_EFFECT_TOOL_CLASS,
  EngineLifecycleObservationSession,
  ExternalLifecycleWitnessDaemon,
  buildImplementationArgs,
  buildReviewArgs,
  assertSemanticRouteFresh,
  buildSupervisedHostGatewayArgs,
  buildSupervisedHostSystemdArgs,
  buildSupervisedHostWorkerArgs,
  createBoundedUnixLifecycleObserver,
  createFileReplayStore,
  createEngineLifecycleObservationSession,
  createHostPinnedTrustedIntakeVerifier,
  createInMemoryReplayStore,
  compileSupervisedEngineBridgeContract,
  compileSupervisedHostPreflight,
  compileSupervisedProductionSubstrateContract,
  compileSemanticWitnessRoute,
  compileProbeEffectProfile,
  compileEngineAcceptanceProfile,
  createAcceptanceDisabledCoordinatorResult,
  createEffectsDisabledBrokerResult,
  createSemanticWitnessAdapter,
  createSemanticWitnessSession,
  createProbeEffectActionAuthority,
  createProbeEffectSession,
  createEngineAcceptanceCoordinator,
  createEngineAcceptanceSession,
  createEngineActionAuthority,
  getAutopilotEngineControlSinkInventory,
  getRequiredActionCatalogBindingIds,
  getSupervisedEngineBridgeAbi,
  getSupervisedEngineBridgeAbiHash,
  getSupervisedProductionSubstrateAbi,
  getSupervisedProductionSubstrateAbiHash,
  getSupervisedProductionDurableAbi,
  getSupervisedProductionDurableAbiHash,
  reviewLoopResultBlocked,
  reviewResultBlocked,
  validateExtraArgs,
  validateImplementerRoster,
  validateExtraReviewArgs,
  validateReviewRoster,
  normalizeEngineLifecycleObservationConfig,
  normalizeAuthenticatedIntakeKeyring,
  normalizeExternalLifecycleWitnessClientConfig,
  normalizeExternalLifecycleWitnessDaemonConfig,
  normalizeAcceptanceDisabledCoordinatorResult,
  normalizeSupervisedProductionDurableAvailabilityDisclosure,
  normalizeSupervisedProductionDurableBinding,
  normalizeSupervisedProductionDurableBrokerResult,
  normalizeSupervisedProductionDurableCoordinatorResult,
  normalizeSupervisedProductionDurableCoordinatorRequest,
  normalizeSupervisedProductionDurableEnvelope,
  normalizeSupervisedProductionDurableRevocationResult,
  normalizeSupervisedProductionDurableServiceAvailabilitySnapshot,
  normalizeSupervisedProductionDurableWitnessResult,
  normalizeSupervisedProductionDurableWitnessRequest,
  normalizeCoordinatorRequest,
  normalizeEffectsDisabledBrokerResult,
  normalizeProbeEffectProfile,
  normalizeEngineAcceptanceProfile,
  normalizeServiceEnvelope,
  resolveReviewLoop,
  resumeProbeEffectSession,
  resumeSemanticWitnessSession,
  resolveReviewLoopJson,
  parseReviewLoopOutput,
  parseCanonicalJsonBytes,
  preflightSupervisedHostRuntime,
  normalizeSupervisedEngineTrustedIntakeBinding,
  normalizeWitnessRequest,
  validateAutopilotEngineControlSinkInventory,
  validateReviewLoopConfig,
  verifySupervisedEngineBridgeContract,
  verifyHostPinnedAuthenticatedIntake,
  verifySupervisedHostPreflight,
  verifySupervisedProductionSubstrateContract,
  findJsonObjectCandidates,
  looksLikeReviewLoopConfig,
  RESOLVE_REVIEW_LOOP,
  invokeSocketRequest,
  ...executionProfile,
  ...ownerKernel,
};
