#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const HELP_TEXT = `Usage: node scripts/scaffold-config.js <target-dir> [--detect <json-file>] [--force] [--dry-run] [--help]

<target-dir>
  Required target repository directory to scaffold.

--detect <file>
  Read detect JSON from this file. If omitted, run scripts/project-detect.js.

--force
  Overwrite existing generated configs even when they differ from scaffold output.

--dry-run
  Show what WOULD be written/skipped without writing anything.

--help
  Show this help text and exit 0.
`;

const RUNTIME_GITIGNORE_BLOCK = `# autopilot runtime state (keep .claude/*-config.md tracked)
.claude/tasks/
.claude/*-state.json
.claude/knowledge/
.claude/.qc/
`;

const GITIGNORE_MARKER = '# autopilot runtime state (keep .claude/*-config.md tracked)';
// Fallback when detect found NO doc dir (project_paths null). Default to the
// plural `docs/` — the common modern convention and what the golden output uses;
// the detector picks up an existing `doc/` (singular) when present.
const DEFAULT_PATHS = {
  projects_dir: 'docs/projects/',
  plans_dir: 'docs/plans/',
  backlog: 'docs/BACKLOG.md',
  index: 'docs/projects/INDEX.md',
  archive_dir: 'docs/projects/_archive/',
};

function printUsageAndExit(code) {
  process.stdout.write(HELP_TEXT);
  process.exit(code);
}

function resolveDetectionTarget(rawArgs) {
  const args = Array.from(rawArgs);
  if (args.includes('-h') || args.includes('--help')) {
    printUsageAndExit(0);
  }

  let targetArg = null;
  let detectFile = null;
  let force = false;
  let dryRun = false;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === '--detect') {
      detectFile = args[i + 1];
      if (!detectFile) {
        printUsageAndExit(2);
      }
      i += 1;
      continue;
    }

    if (arg === '--force') {
      force = true;
      continue;
    }

    if (arg === '--dry-run') {
      dryRun = true;
      continue;
    }

    if (arg.startsWith('-')) {
      printUsageAndExit(2);
    }

    if (targetArg === null) {
      targetArg = arg;
    } else {
      printUsageAndExit(2);
    }
  }

  if (!targetArg) {
    printUsageAndExit(2);
  }

  return {
    targetDir: path.resolve(process.cwd(), targetArg),
    detectFile,
    force,
    dryRun,
  };
}

function readDetectFromFile(filePath) {
  const raw = fs.readFileSync(filePath, 'utf8');
  return JSON.parse(raw);
}

function readDetectByRunning(projectDir) {
  const detectScript = path.join(__dirname, 'project-detect.js');
  const output = execFileSync('node', [detectScript, projectDir], { encoding: 'utf8' });
  return JSON.parse(output);
}

function getProjectPaths(detect) {
  const p = detect && detect.project_paths ? detect.project_paths : null;
  return {
    projects_dir: p && p.projects_dir ? p.projects_dir : DEFAULT_PATHS.projects_dir,
    plans_dir: p && p.plans_dir ? p.plans_dir : DEFAULT_PATHS.plans_dir,
    backlog: p && p.backlog ? p.backlog : DEFAULT_PATHS.backlog,
    index: p && p.index ? p.index : DEFAULT_PATHS.index,
    archive_dir: p && p.archive_dir ? p.archive_dir : DEFAULT_PATHS.archive_dir,
  };
}

function getWorkspacePackages(detect) {
  if (!detect || !detect.workspace || !Array.isArray(detect.workspace.packages)) return [];
  return detect.workspace.packages.slice().sort();
}

function hasCommands(value) {
  return typeof value === 'string' && value.trim().length > 0;
}

function buildQualityTestCommand(commands) {
  const test = hasCommands(commands && commands.test) ? commands.test : '';
  const typecheck = hasCommands(commands && commands.typecheck) ? commands.typecheck : '';
  if (typecheck && test) return `${typecheck} && ${test}`;
  return typecheck || test || 'not detected';
}

function buildSourceGlobsForScan(detect) {
  // Use the DETECTED source paths (packages/<pkg>/src/), not bare package
  // basenames — `relay`/`shared` would yield non-existent `relay/src`.
  const protectedPaths = detect && Array.isArray(detect.protected_path_candidates)
    ? detect.protected_path_candidates
    : [];
  if (protectedPaths.length > 0) return protectedPaths;
  return ['src/'];
}

function headerTitle(title) {
  return `# ${title} — Project Config (generated by autopilot:onboard; edit freely)\n`;
}

function generateNextConfig(paths) {
  return `${headerTitle('Next')}\n## Scan Sources\n- Projects index: \`${paths.index}\`\n- Plans index: \`${paths.plans_dir}\`\n- Backlog: \`${paths.backlog}\`\n`;
}

function generateProjectLifecycleConfig(paths) {
  return `${headerTitle('Project Lifecycle')}\n## Project Paths\n- Projects directory: \`${paths.projects_dir}\`\n- Plans directory: \`${paths.plans_dir}\`\n- Archive: \`${paths.archive_dir}\`\n- Backlog: \`${paths.backlog}\`\n- Index: \`${paths.index}\`\n`;
}

function generateDispatchConfig(superpowersInstalled) {
  const lines = [headerTitle('Dispatch'), '# Superpowers is not installed. Edit this file to add superpowers preference chains.'];
  if (superpowersInstalled) {
    lines[1] = '# Superpowers detected. Edit chains here if you want superpowers preference.';
  }
  lines.push('## Parallel Dispatch');
  lines.push('- native');
  lines.push('', '## Code Review');
  lines.push('- autopilot:reviewer');
  lines.push('', '## Debugging');
  lines.push('- autopilot:debug');
  lines.push('', '## Testing');
  lines.push('- autopilot:test-strategy');
  lines.push('', '## Profiling');
  lines.push('- autopilot:profiling');
  lines.push('', '## Team');
  lines.push('- autopilot:team');
  lines.push('');
  return lines.join('\n');
}

function generateQualityGateConfig(commands, scanTargets, superpowersInstalled) {
  const testCommand = buildQualityTestCommand(commands);
  // completeness-scan.sh is a SHELL script shipped by autopilot — reference it as
  // prose over the detected source globs (never `node <.sh>`; the consuming repo
  // resolves the autopilot script path itself).
  const scanCommand = `Completeness scan (no stubs/TODO/mock): autopilot \`scripts/completeness-scan.sh\` over ${scanTargets.join(' ')}`;
  const lines = [
    headerTitle('Quality Gate'),
    `## Test Command`,
    `- ${testCommand}`,
    '',
    '## Scan Command',
    `- ${scanCommand}`,
    '',
    '## Code Review',
    '- autopilot:reviewer',
    '',
  ];
  if (!superpowersInstalled) {
    lines.push('# Superpowers not installed. Keep autopilot:reviewer unless you add superpowers preference chains in dispatch-config.md.');
  }
  lines.push('');
  return lines.join('\n');
}

function generateDevFlowConfig(paths, commands, defaultBranch, lintNoop) {
  return `${headerTitle('Dev Flow')}\n## Quality Gate\n- Test command: ${buildQualityTestCommand(commands)}\n- Typecheck command: ${hasCommands(commands && commands.typecheck) ? commands.typecheck : 'not detected'}\n\n## Build & Deploy\n- Build: ${hasCommands(commands && commands.build) ? commands.build : 'not detected'}\n\n## Project Paths\n- Projects directory: \`${paths.projects_dir}\`\n- Backlog: \`${paths.backlog}\`\n\n## Branch Rules\n- Default branch: ${defaultBranch}\n${lintNoop ? '\n## Lint Notes\n- Lint is a no-op in this repo.\n' : ''}\n`;
}

function generateTestStrategyConfig(commands, coverageThresholds) {
  const coverage = coverageThresholds && typeof coverageThresholds === 'object' ? coverageThresholds : {};
  const entries = Object.keys(coverage).sort().map((pkg) => {
    const row = coverage[pkg] || {};
    return `| ${pkg} | ${row.lines ?? ''} | ${row.functions ?? ''} | ${row.branches ?? ''} | ${row.statements ?? ''} |`;
  });
  const table = entries.length === 0
    ? 'No per-package coverage thresholds detected.'
    : `| Package | Lines | Functions | Branches | Statements |\n| --- | --- | --- | --- | --- |\n${entries.join('\n')}`;

  return `${headerTitle('Test Strategy')}\n## Test Commands\n- test: ${hasCommands(commands && commands.test) ? commands.test : 'not detected'}\n- test_watch: ${hasCommands(commands && commands.test_watch) ? commands.test_watch : 'not detected'}\n- typecheck: ${hasCommands(commands && commands.typecheck) ? commands.typecheck : 'not detected'}\n\n## Coverage\n${table}\n`;
}

function generateQcGateConfig(paths) {
  const protectedPaths = Array.isArray(paths) && paths.length > 0 ? paths.join(',') : 'src/';
  return `${headerTitle('qc-gate-config')}\n## Settings (one \`key: value\` per line; first match wins)\n\n- mode: warn\n- protected_paths: ${protectedPaths}\n- evidence: either\n`;
}

function generateSkillRoutingConfig() {
  return `${headerTitle('Skill Routing')}
<!-- TODO(onboard): map THIS project's domain keywords to autopilot skills.
     Read the source/docs for recurring domain terms and route each to the right
     methodology skill. Example rows (delete this comment, add real rows below):
       | wire format / schema        | autopilot:debug          |
       | auth / escaping / injection | autopilot:reviewer       |
       | latency / throughput        | autopilot:profiling      | -->

| Keyword | Invoke |
|---------|--------|
`;
}

function generateDocDriftConfig() {
  return `${headerTitle('Doc-Sync')}\n\n## Domains\n<!-- TODO(onboard): one ### block per doc⇄code domain with focus prose -->\n\ngate_command: node scripts/doc-drift-gate.js\nstaleness_days: 30\n`;
}

function writeOrSkipFile(filePath, relativeName, content, state) {
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (current !== null && current === content) {
    return;
  }

  if (current !== null && !state.force) {
    state.skipped.push(relativeName);
    console.log(`${relativeName}: skipped (hand-edited; --force to overwrite)`);
    return;
  }

  if (!state.dryRun) {
    fs.writeFileSync(filePath, content);
  } else {
    console.log(`${relativeName}: would write`);
  }
  state.written.push(relativeName);
}

// A pre-existing WHOLESALE `.claude/` ignore shadows the generated *-config.md, and
// git CANNOT re-include a file under a fully-excluded parent (a `!.claude/*-config.md`
// negation is silently inert — same gotcha as distill-sync-setup). Detect + warn; we
// cannot auto-fix without rewriting the user's intent.
function claudeDirWholesaleIgnored(gitignoreText) {
  return gitignoreText
    .split(/\r?\n/)
    .map((l) => l.trim())
    .some((l) => /^!?\/?\.claude\/?$/.test(l) && !l.startsWith('!'));
}

function updateGitignore(targetDir, dryRun) {
  const gitignorePath = path.join(targetDir, '.gitignore');
  let current = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf8') : '';
  if (claudeDirWholesaleIgnored(current)) {
    console.warn(
      '.gitignore WARNING: a wholesale `.claude/` ignore rule is present — the generated ' +
      '`.claude/*-config.md` will stay UNTRACKED, and git cannot re-include them under a ' +
      'fully-excluded parent. Replace `.claude/` with the specific runtime-state paths ' +
      '(`.claude/tasks/`, `.claude/*-state.json`, `.claude/knowledge/`, `.claude/.qc/`) so ' +
      'the configs are tracked.'
    );
  }
  if (current.includes(GITIGNORE_MARKER)) {
    return false;
  }

  let next = current;
  if (next && !next.endsWith('\n')) {
    next += '\n';
  }
  if (next) {
    next += '\n';
  }
  next += RUNTIME_GITIGNORE_BLOCK;
  if (!dryRun) {
    fs.writeFileSync(gitignorePath, next);
  } else {
    console.log('.gitignore: would update (autopilot runtime state block)');
  }
  return true;
}

function main() {
  let parsed;
  try {
    parsed = resolveDetectionTarget(process.argv.slice(2));
  } catch {
    printUsageAndExit(2);
  }

  const state = {
    targetDir: parsed.targetDir,
    force: parsed.force,
    dryRun: parsed.dryRun,
    written: [],
    skipped: [],
  };

  let detect;
  try {
    detect = parsed.detectFile
      ? readDetectFromFile(parsed.detectFile)
      : readDetectByRunning(parsed.targetDir);
  } catch (err) {
    console.error(`error: failed to load detect data: ${err && err.message ? err.message : String(err)}`);
    process.exit(1);
  }

  const paths = getProjectPaths(detect);
  const commands = detect && detect.commands ? detect.commands : {};
  const superpowers = detect && detect.installed_plugins && detect.installed_plugins.superpowers === true;
  const scanTargets = buildSourceGlobsForScan(detect);
  const defaultBranch = detect && detect.default_branch ? detect.default_branch : 'main';
  const lintNoop = detect && detect.commands && detect.commands.lint_is_noop === true;
  const coverageThresholds = detect && detect.coverage_thresholds ? detect.coverage_thresholds : {};
  const protectedPaths = detect && Array.isArray(detect.protected_path_candidates)
    ? detect.protected_path_candidates
    : [];

  const files = {
    'next-config.md': generateNextConfig(paths),
    'project-lifecycle-config.md': generateProjectLifecycleConfig(paths),
    'dispatch-config.md': generateDispatchConfig(superpowers),
    'quality-gate-config.md': generateQualityGateConfig(commands, scanTargets, superpowers),
    'dev-flow-config.md': generateDevFlowConfig(paths, commands, defaultBranch, lintNoop),
    'test-strategy-config.md': generateTestStrategyConfig(commands, coverageThresholds),
    'qc-gate-config.md': generateQcGateConfig(protectedPaths),
    'skill-routing.md': generateSkillRoutingConfig(),
    'doc-drift-config.md': generateDocDriftConfig(),
  };

  const claudeDir = path.join(state.targetDir, '.claude');
  try {
    if (!state.dryRun && !fs.existsSync(claudeDir)) {
      fs.mkdirSync(claudeDir, { recursive: true });
    }

    Object.entries(files).forEach(([name, content]) => {
      const rel = `.claude/${name}`;
      writeOrSkipFile(path.join(claudeDir, name), rel, content, state);
    });

    const gitignoreUpdated = updateGitignore(state.targetDir, state.dryRun);
    if (gitignoreUpdated) {
      console.log('.gitignore: runtime state block would be added');
    }

    console.log(JSON.stringify({
      written: state.written,
      skipped: state.skipped,
      gitignore_updated: gitignoreUpdated,
    }));
    process.exit(0);
  } catch (err) {
    console.error(`error: ${err && err.message ? err.message : String(err)}`);
    process.exit(1);
  }
}

main();
