'use strict';

const { canonicalJson, cloneCanonical, isSha256, sha256 } = require('./canonical');
const {
  classifyContractLeg,
  contractArtifactIds,
  evaluateAcceptancePredicate,
  manifestHash,
  normalizeAcceptanceAuthority,
  normalizeAcceptanceAuthorityHeader,
  normalizeAcceptanceSnapshot,
} = require('./acceptance');
const {
  ACTION_CLASS_RANK,
  assertIndependentAuthorityBindings,
  actionDescriptorHash,
  actionMatchesDescriptor,
  normalizeActionAuthority,
  normalizeActionCancellationResult,
  normalizeActionCatalog,
  normalizeActionDescriptor,
  normalizeActionExecutionResult,
  normalizeExecutionAuthorization,
  normalizeExecutionPermit,
  normalizeFrozenActionDescriptor,
  normalizeFrozenHostCapabilityVerifierBinding,
  normalizeHostCapability,
  normalizeVerifiedActionOutcome,
  receiptIsWithinBrokerRoot,
  validateHostCapabilityCoverage,
} = require('./actions');
const { OwnerKernelBlockedError, OwnerKernelError } = require('./errors');
const { EVENT_TYPES, OWNER_EVENT_SCHEMA_VERSION, validateEventShape, verifyEvent } = require('./events');
const { OwnerKernel } = require('./kernel');
const {
  HEADER_RECORD_TYPE,
  LEDGER_SCHEMA_VERSION,
  createLedgerHeader,
  parseLedgerJsonl,
  replayFromLatestCheckpoint,
  serializeLedger,
  validateLedgerHeader,
  verifyLedger,
} = require('./ledger');
const {
  ACTION_CLASSES,
  GOVERNANCE_SCHEMA_VERSION,
  SUPPORTED_MODES,
  freezeAcceptanceContract,
  resolveGovernancePolicy,
} = require('./policy');
const { deriveDisclosure, stateProjection } = require('./state');
const { MemoryWitness, normalizeWitnessBinding } = require('./witness');
const {
  SEMANTIC_AUTHORITY_SCHEMA_VERSION,
  SEMANTIC_WITNESS_ROUTE_VERSION,
  createSemanticAuthorityHeader,
  normalizeSemanticAuthorityHeader,
  normalizeSemanticRoute,
  semanticRouteHash,
} = require('./semantic-authority');
const {
  ASSURANCE_PROFILES,
  LEGACY_LEVELS,
  LEVEL_TOPOLOGIES,
  LEVEL_TRANSLATION_SCHEMA_VERSION,
  createShadowTranslationEnvelope,
  deriveTranslationStatus,
  normalizeRedLines,
  translateLegacyLevel,
  verifyShadowTranslationEnvelope,
} = require('./compatibility');
const {
  SHADOW_TRANSLATION_CONTRACT_ID,
  SHADOW_TRANSLATION_LEVEL,
  ShadowTranslationRuntime,
} = require('./shadow-translation');

module.exports = {
  ACTION_CLASSES,
  ACTION_CLASS_RANK,
  ASSURANCE_PROFILES,
  assertIndependentAuthorityBindings,
  EVENT_TYPES,
  GOVERNANCE_SCHEMA_VERSION,
  HEADER_RECORD_TYPE,
  LEDGER_SCHEMA_VERSION,
  LEGACY_LEVELS,
  LEVEL_TOPOLOGIES,
  LEVEL_TRANSLATION_SCHEMA_VERSION,
  MemoryWitness,
  OWNER_EVENT_SCHEMA_VERSION,
  OwnerKernel,
  OwnerKernelBlockedError,
  OwnerKernelError,
  SHADOW_TRANSLATION_CONTRACT_ID,
  SHADOW_TRANSLATION_LEVEL,
  SEMANTIC_AUTHORITY_SCHEMA_VERSION,
  SEMANTIC_WITNESS_ROUTE_VERSION,
  ShadowTranslationRuntime,
  SUPPORTED_MODES,
  canonicalJson,
  classifyContractLeg,
  cloneCanonical,
  contractArtifactIds,
  createLedgerHeader,
  createSemanticAuthorityHeader,
  createShadowTranslationEnvelope,
  deriveTranslationStatus,
  deriveDisclosure,
  evaluateAcceptancePredicate,
  freezeAcceptanceContract,
  isSha256,
  actionDescriptorHash,
  actionMatchesDescriptor,
  normalizeActionAuthority,
  normalizeAcceptanceAuthority,
  normalizeAcceptanceAuthorityHeader,
  normalizeAcceptanceSnapshot,
  normalizeActionCancellationResult,
  normalizeActionCatalog,
  normalizeActionDescriptor,
  normalizeActionExecutionResult,
  normalizeExecutionAuthorization,
  normalizeExecutionPermit,
  normalizeFrozenActionDescriptor,
  normalizeFrozenHostCapabilityVerifierBinding,
  normalizeHostCapability,
  normalizeRedLines,
  normalizeSemanticAuthorityHeader,
  normalizeSemanticRoute,
  normalizeWitnessBinding,
  normalizeVerifiedActionOutcome,
  manifestHash,
  parseLedgerJsonl,
  replayFromLatestCheckpoint,
  resolveGovernancePolicy,
  receiptIsWithinBrokerRoot,
  serializeLedger,
  semanticRouteHash,
  sha256,
  stateProjection,
  translateLegacyLevel,
  validateEventShape,
  validateHostCapabilityCoverage,
  validateLedgerHeader,
  verifyEvent,
  verifyLedger,
  verifyShadowTranslationEnvelope,
};
