#!/usr/bin/env bash
# check-canonical-invariants.sh — guard cross-file invariants that the byte-for-byte
# mirror checks (sync-version.js --check, sync-agent-bodies.sh --check) CANNOT see,
# because the files involved are intentionally NOT byte-equal.
#
# Two modes, both seeded from an INLINE table below (no separate data file — with a
# handful of seeds a TSV would be an orphan with no CLAUDE.md home; ponytail's own
# check-rule-copies.js inlines its table for the same reason):
#
#   repeat    — a pinned VERBATIM phrase must co-exist in EVERY listed file. Use when
#               two or more files independently RESTATE the same rule (e.g. the unified
#               severity vocabulary). Deleting the phrase from any one file → exit 1
#               naming that file + the phrase.
#
#   reference — file A REFERENCES a section in file B (A does not repeat B's body). Assert
#               (1) A still contains the exact cross-ref anchor string, AND (2) the
#               referenced heading still exists in B. Catches the STRUCTURAL break — anchor
#               renamed/deleted, or heading renamed/deleted — in the correct direction.
#               KNOWN LIMIT: it does NOT catch a body-reword of B's section while the
#               heading stays put. That residual is a human-review concern, not a silent
#               over-claim (see the plan's KR2 scope note).
#
# ── SAME-COMMIT UPDATE RITUAL (read before you reword a guarded rule) ──────────────
#   Any edit to a rule-text that this script pins MUST update the inline seed in the
#   SAME commit. Otherwise the gate is noise: a legitimate reword trips exit 1, the
#   author bypasses the hook "just this once", and the gate is dead. The negative test
#   for a reword is "reword + update the seed in one commit → exit 0". If you find
#   yourself wanting to bypass this hook, update the seed instead.
#
# USAGE:  scripts/check-canonical-invariants.sh
# OUTPUT: one line per checked invariant; ERROR lines for failures.
# EXIT:   0 = all invariants hold
#         1 = at least one invariant broken (each printed with the file + phrase)
#         2 = usage / environment error (e.g. a seeded file path does not exist)

set -uo pipefail

case "${1:-}" in
  --help|-h)
    sed -n '2,38p' "$0" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
esac

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

IS_PLUGIN=0
if [[ "$REPO" == *"/platforms/codex/plugin" ]]; then
  IS_PLUGIN=1
fi

FAILS=0
ENV_ERR=0

ok()   { echo "  ✓ $1"; }
bad()  { echo "  ✗ $1" >&2; FAILS=$((FAILS + 1)); }
envx() { echo "  ! $1" >&2; ENV_ERR=1; }

# ── repeat-mode invariant ──────────────────────────────────────────────────────────
# A pinned verbatim phrase that must appear in every listed file. fgrep (-F) so glyphs
# and slashes are matched literally, never as a regex.
check_repeat() {
  local label="$1"; local phrase="$2"; shift 2
  local file missing=0
  for file in "$@"; do
    if [ ! -f "$file" ]; then
      if [ "$IS_PLUGIN" = "1" ]; then
        continue
      fi
      envx "repeat[$label]: seeded file does not exist: $file"
      missing=1
      continue
    fi
    if ! grep -Fq -- "$phrase" "$file"; then
      bad "repeat[$label]: missing verbatim phrase in $file"
      echo "      phrase: $phrase" >&2
      missing=1
    fi
  done
  [ "$missing" = "0" ] && ok "repeat[$label]: present in all ${#} files"
}

# ── mirror-mode invariant ──────────────────────────────────────────────────────────
# canonical file → generated copies must be BYTE-EQUAL real files. The copies exist so
# in-skill reference paths keep resolving (zero link breakage), but they are GENERATED
# ARTIFACTS regenerated by scripts/sync-model-routing.sh — a hand-edit to a copy (or a
# copy degrading back to a symlink, which rsync -L / payload sync would divorce) trips
# this gate. Fix: edit the canonical, then run scripts/sync-model-routing.sh.
check_mirror() {
  local label="$1" canonical="$2"; shift 2
  local copy broke=0
  if [ ! -f "$canonical" ]; then
    if [ "$IS_PLUGIN" = "1" ]; then
      return 0
    fi
    envx "mirror[$label]: canonical does not exist: $canonical"; return
  fi
  for copy in "$@"; do
    if [ -L "$copy" ]; then
      bad "mirror[$label]: $copy is a symlink — copies must be REAL generated files (run scripts/sync-model-routing.sh)"
      broke=1
      continue
    fi
    if [ ! -f "$copy" ]; then
      if [ "$IS_PLUGIN" = "1" ]; then
        continue
      fi
      envx "mirror[$label]: seeded copy does not exist: $copy"; broke=1; continue
    fi
    if ! cmp -s -- "$canonical" "$copy"; then
      bad "mirror[$label]: $copy is out of byte-parity with $canonical (edit the CANONICAL, then run scripts/sync-model-routing.sh — never hand-edit a copy)"
      broke=1
    fi
  done
  [ "$broke" = "0" ] && ok "mirror[$label]: all ${#} copies byte-equal to canonical"
}

# ── canonical-link lint ────────────────────────────────────────────────────────────
# A byte-parity canonical must not contain RELATIVE markdown links: each copy lives at
# a different directory depth, so `../foo.md` resolves to a different (wrong) target in
# every copy. Repo-root-stable paths or absolute URLs only. (Future-proofing — 0 hits
# today; gpt-R1-G5 narrowed to this lint.)
check_no_relative_links() {
  local label="$1" file="$2"
  if [ ! -f "$file" ]; then
    if [ "$IS_PLUGIN" = "1" ]; then
      return 0
    fi
    envx "no-rel-links[$label]: file does not exist: $file"; return
  fi
  local hits
  hits=$(grep -nE '\]\((\.\./|\./)' -- "$file" || true)
  if [ -n "$hits" ]; then
    bad "no-rel-links[$label]: $file contains relative markdown links (breaks under byte-parity copies at different depths)"
    echo "$hits" | sed 's/^/      /' >&2
  else
    ok "no-rel-links[$label]: no relative links in canonical"
  fi
}

# ── reader-allowlist invariant ─────────────────────────────────────────────────────
# A token whose READERS form a CLOSED set. Built for the unratified_* salvage columns
# (verdict-bytes preservation, v2.34.33): content-verified but transport-unratified
# data exists ONLY for human adjudication — no consumer may derive authority from it,
# and the cheapest durable enforcement is "any new file that mentions the token must
# be explicitly allowlisted here" (g1 disposition 2162610231 + 6d7fb3b4). Scans the
# whole tree (tracked or not) so a rogue consumer is caught before it ever lands.
check_reader_allowlist() {
  local label="$1"; local token="$2"; shift 2
  local allowed=("$@")
  local file hit candidate bad_found=0
  while IFS= read -r file; do
    hit=0
    for candidate in "${allowed[@]}"; do
      # shellcheck disable=SC2254
      case "$file" in
        $candidate) hit=1; break ;;
      esac
    done
    if [ "$hit" = "0" ]; then
      bad "reader-allowlist[$label]: $file mentions '$token' but is not in the closed reader allowlist — unratified data is HUMAN-adjudication-only, never authority (docs/plans/2026-08-21-verdict-bytes-preservation.md §2). If this file is a legitimate producer/display/test, add it to the seed in the SAME commit."
      bad_found=1
    fi
  done < <(grep -rIl \
      --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.claude \
      --exclude-dir=.autopilot --exclude-dir=worktrees \
      -- "$token" . 2>/dev/null | sed 's|^\./||')
  [ "$bad_found" = "0" ] && ok "reader-allowlist[$label]: every '$token' mention is allowlisted"
}

# ── reference-mode invariant ───────────────────────────────────────────────────────
# referencing_file must contain anchor_in_referrer; canonical_file must contain
# heading_in_canonical. Both are fixed-string matches.
check_reference() {
  local label="$1"
  local referencing_file="$2" anchor_in_referrer="$3"
  local canonical_file="$4" heading_in_canonical="$5"
  local broke=0

  if [ ! -f "$referencing_file" ]; then
    if [ "$IS_PLUGIN" = "1" ]; then
      return 0
    fi
    envx "reference[$label]: referencing file does not exist: $referencing_file"; return
  fi
  if [ ! -f "$canonical_file" ]; then
    if [ "$IS_PLUGIN" = "1" ]; then
      return 0
    fi
    envx "reference[$label]: canonical file does not exist: $canonical_file"; return
  fi

  if ! grep -Fq -- "$anchor_in_referrer" "$referencing_file"; then
    bad "reference[$label]: $referencing_file lost the cross-ref anchor"
    echo "      anchor: $anchor_in_referrer" >&2
    broke=1
  fi
  if ! grep -Fxq -- "$heading_in_canonical" "$canonical_file"; then
    bad "reference[$label]: $canonical_file lost the referenced heading (structural rename/deletion)"
    echo "      heading: $heading_in_canonical" >&2
    broke=1
  fi
  [ "$broke" = "0" ] && ok "reference[$label]: anchor + heading both intact"
}

echo "check-canonical-invariants — cross-file invariant gate"
echo ""

# ════════════════════════════════════════════════════════════════════════════════════
# INLINE SEED TABLE — keep in lockstep with the guarded rule text (same-commit ritual).
# ════════════════════════════════════════════════════════════════════════════════════

# repeat #1 — unified severity vocabulary line. Every file that independently restates
# the 4-tier vocabulary must carry it verbatim. If you change the vocabulary, change it
# here AND in every listed file in the same commit.
check_repeat "severity-vocab" \
  "🔴 Critical / 🟠 Major / 🟡 Minor / 🔵 Suggestion" \
  "CLAUDE.md" \
  "agents/reviewer.md" \
  "references/blind-dispatch.md" \
  "skills/quality-pipeline/_base/prohibited-behaviors.md" \
  "skills/quality-pipeline/references/code-review.md"

# repeat #2 — the /l4 /l5 width-fan-out disjointness carve-out. This single sentence is
# LOAD-BEARING: it states the gate certifies FILES ONLY (not behavior), so the green
# disjointness stamp must never shrink the depth-0 qc. If either doc drops/rewords it the
# safety invariant silently erodes. Reword ritual: change the sentence here AND in both
# files in one commit.
check_repeat "disjointness-carve-out" \
  "The disjointness gate certifies files only, not behavior." \
  "references/blind-dispatch.md" \
  "skills/ceo-agent/references/level-front-door.md"

# repeat #2b — the engine-unavailable error-string format contract. dispatch-hetero.sh
# authors "engine unavailable ($CLASSIFIED_ERROR): ..." (two emit sites) and
# autopilot-engine.js parseEngineUnavailableClass parses the same prefix by regex to map
# the on_engine_unavailable policy; a reworded prefix silently degrades every capacity
# death to escalate (fails closed but wrong action). Reword ritual: change the prefix at
# BOTH dispatch emit sites AND the engine regex AND this seed in one commit.
check_repeat "engine-unavailable-error-prefix" \
  "engine unavailable (" \
  "scripts/dispatch-hetero.sh" \
  "src/engine/autopilot-engine.js" \
  "hooks/tests/autopilot-engine.test.sh"

# The regex itself (escaped paren form) — pins the actual parse site, not just the
# comment above it, so deleting/rewording parseEngineUnavailableClass trips the gate.
check_repeat "engine-unavailable-parse-regex" \
  'engine unavailable \(([a-z_]+)\)' \
  "src/engine/autopilot-engine.js"

# reference #1 — reviewer.md REFERENCES code-review.md's Invocation section (it does not
# repeat the body). Assert reviewer.md still names the canonical anchor AND the heading
# still exists in code-review.md. Catches a structural rename/deletion of "## Invocation".
check_reference "reviewer→code-review/Invocation" \
  "agents/reviewer.md"                               "code-review.md) Invocation §" \
  "skills/quality-pipeline/references/code-review.md" "## Invocation"

# repeat #3 — S-scope-gate block invariants. Seed the TaskCreate title line, the three
# indicator lines, and the "Mark this task ONLY when" line across dev-flow and ceo-agent.
check_repeat "s-scope-gate-title" \
  'TaskCreate: "S-scope-gate: Evaluate scope before every commit"' \
  "skills/dev-flow/SKILL.md" \
  "skills/ceo-agent/SKILL.md"

check_repeat "s-scope-gate-ind1" \
  '    (1) Fewer than 3 commits on this task so far?' \
  "skills/dev-flow/SKILL.md" \
  "skills/ceo-agent/SKILL.md"

check_repeat "s-scope-gate-ind2" \
  '    (2) Fewer than 3 different modules touched?' \
  "skills/dev-flow/SKILL.md" \
  "skills/ceo-agent/SKILL.md"

check_repeat "s-scope-gate-ind3" \
  '    (3) No features added beyond original goal?' \
  "skills/dev-flow/SKILL.md" \
  "skills/ceo-agent/SKILL.md"

check_repeat "s-scope-gate-mark" \
  '  Mark this task ONLY when: work is complete AND scope stayed S throughout (all YES),' \
  "skills/dev-flow/SKILL.md" \
  "skills/ceo-agent/SKILL.md"

# reference #2 — ceo-agent references dev-flow's canonical Scope Completeness Audit heading.
check_reference "ceo-agent→dev-flow/ScopeCompletenessAudit" \
  "skills/ceo-agent/SKILL.md" "**Scope Completeness Audit**" \
  "skills/dev-flow/SKILL.md" "#### Scope Completeness Audit (MANDATORY before phase TaskCreate)"

# reference #3 — reviewer references blind-dispatch's verifier-isolation section.
check_reference "reviewer→blind-dispatch/VerifierIsolation" \
  "agents/reviewer.md" "(canonical: references/blind-dispatch.md § Verifier isolation)" \
  "references/blind-dispatch.md" "## Verifier isolation — artifacts only, never the implementer's self-report (EVERY dispatch)"

# reference #4 — code-review references blind-dispatch's verifier-isolation section.
check_reference "code-review→blind-dispatch/VerifierIsolation" \
  "skills/quality-pipeline/references/code-review.md" "(canonical: references/blind-dispatch.md § Verifier isolation)" \
  "references/blind-dispatch.md" "## Verifier isolation — artifacts only, never the implementer's self-report (EVERY dispatch)"

# reader-allowlist #1 — the unratified_* salvage columns. Producers, schemas,
# display-only projections, the pass-through validator, the codex PLUGIN mirror
# subtree (kept byte-equal to canonical by sync-codex-plugin-skills --check — the
# narrower seed is deliberate: platform-NATIVE sources like platforms/codex/hooks/*
# have no canonical counterpart and no parity gate, so they stay OUTSIDE the
# allowlist; round-1 review 2026-08-21), tests, and docs. Everything else that
# mentions the token is a rogue consumer.
check_reader_allowlist "unratified-columns" \
  "unratified" \
  "scripts/dispatch-review.sh" \
  "scripts/dispatch-plan-review.js" \
  "scripts/dispatch-status.js" \
  "scripts/lib/plan-review-normalize.js" \
  "scripts/lib/plan-review-panel.js" \
  "scripts/check-canonical-invariants.sh" \
  "src/runners/review.js" \
  "schemas/*" \
  "platforms/codex/plugin/*" \
  "hooks/tests/*" \
  "docs/*" \
  "CHANGELOG.md" \
  "README.md" \
  "README.zh-TW.md"

# reference #5 — level-front-door references code-review's Panel aggregation section.
check_reference "level-front-door→code-review/PanelAggregation" \
  "skills/ceo-agent/references/level-front-door.md" "code-review.md) § \"Panel aggregation\"" \
  "skills/quality-pipeline/references/code-review.md" "## Panel aggregation (multi-reviewer / disjoint-family qc)"


# mirror #1 — model-routing.md: references/model-routing.md is canonical; the four
# in-skill copies are generated (single maintenance truth — plan 2026-07-04
# surface-area-reduction B3). Regenerate: scripts/sync-model-routing.sh.
check_mirror "model-routing" \
  "references/model-routing.md" \
  "skills/dev-flow/references/model-routing.md" \
  "skills/quality-pipeline/references/model-routing.md" \
  "skills/survey/references/model-routing.md" \
  "skills/think-tank/references/model-routing.md"

# lint #1 — the model-routing canonical must stay free of relative links (see
# check_no_relative_links rationale).
check_no_relative_links "model-routing" "references/model-routing.md"

echo ""
if [ "$ENV_ERR" = "1" ]; then
  echo "❌ environment error — a seeded path is wrong (fix the seed table)" >&2
  exit 2
fi
if [ "$FAILS" -eq 0 ]; then
  echo "✅ all canonical invariants hold"
  exit 0
else
  echo "❌ $FAILS canonical invariant(s) broken" >&2
  exit 1
fi
